version: 2
updates:
  # Atualizações para npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    # Atualizações de segurança separadas
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major"]

  # Atualizações para Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"
      include: "scope"
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major"]

  # Atualizações para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "actions"
      include: "scope"
