name: Label Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar label 'automerge' a PRs do Dependabot
        if: github.actor == 'dependabot[bot]'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            automerge
