name: CI - Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Check out the repository
      - uses: actions/setup-node@v4 # Set up Node.js environment
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci # Install dependencies
      - run: npm run migrate
      - run: npm run test:unit
        env:
          APP_PORT: 3000
          NODE_ENV: test
          JWT_SECRET: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: fake_url
